name: Build & Test
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install dependencies
        run: |
          yarn install
      - name: Run Jest tests locally
        run: |
          yarn test
  node14-tests:
    uses: ./.github/workflows/test-with-docker.yml
    with:
      node_version: "14"
      jest_versions: "19 20 21 22 23 24 25 26 27 28 29"
  node16-tests:
    uses: ./.github/workflows/test-with-docker.yml
    with:
      node_version: "16"
      jest_versions: "19"
